# vbtc.github.io configuration

title: VBTC Blog
author: VBTC
email: support@vbtc.vn
description: News and announcements regarding VBTC, the first Bitcoin live exchange in Vietnam
baseurl: "/"
url: "https://vbtc.github.io"
show_excerpts: true

twitter_username: vbtc_vietnam
facebook_username: VBTC.vn
github_username: vbtc
rss: feed.xml

google_analytics: UA-134715319-1

permalink: /:year/:categories/:title
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed